// Types pour les événements
export interface Event {
  id: string
  title: string
  description: string
  date: string
  time: string
  location: string
  capacity: number
  remainingSeats: number
  category: string
  image?: string
}

// Données initiales pour les événements
export const initialEvents: Event[] = [
  {
    id: "1",
    title: "Conférence Tech 2024",
    description: "Une conférence sur les dernières tendances technologiques et l'innovation.",
    date: "2024-06-15",
    time: "09:00",
    location: "Centre des Congrès, Paris",
    capacity: 200,
    remainingSeats: 150,
    category: "Technologie",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "2",
    title: "Concert de Jazz",
    description: "Un concert de jazz avec des artistes internationaux renommés.",
    date: "2024-07-20",
    time: "20:00",
    location: "Salle Pleyel, Paris",
    capacity: 500,
    remainingSeats: 200,
    category: "Musique",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "3",
    title: "Atelier de Cuisine",
    description: "Apprenez à cuisiner des plats gastronomiques avec un chef étoilé.",
    date: "2024-06-30",
    time: "14:00",
    location: "École de Cuisine, Lyon",
    capacity: 20,
    remainingSeats: 5,
    category: "Gastronomie",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "4",
    title: "Exposition d'Art Contemporain",
    description: "Découvrez les œuvres d'artistes contemporains émergents.",
    date: "2024-08-10",
    time: "10:00",
    location: "Galerie Moderne, Marseille",
    capacity: 100,
    remainingSeats: 80,
    category: "Art",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "5",
    title: "Séminaire sur le Développement Durable",
    description: "Discussions et ateliers sur les pratiques durables pour les entreprises.",
    date: "2024-09-05",
    time: "09:30",
    location: "Centre d'Affaires, Bordeaux",
    capacity: 150,
    remainingSeats: 100,
    category: "Environnement",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "6",
    title: "Festival de Cinéma",
    description: "Projections de films indépendants et rencontres avec des réalisateurs.",
    date: "2024-10-15",
    time: "18:00",
    location: "Cinémathèque, Nice",
    capacity: 300,
    remainingSeats: 250,
    category: "Cinéma",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "7",
    title: "Salon du Livre",
    description: "Rencontrez vos auteurs préférés et découvrez les nouveautés littéraires.",
    date: "2024-11-20",
    time: "10:00",
    location: "Palais des Congrès, Lille",
    capacity: 500,
    remainingSeats: 400,
    category: "Littérature",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "8",
    title: "Marathon de Paris",
    description: "Participez à la course mythique à travers les rues de la capitale.",
    date: "2024-04-07",
    time: "08:00",
    location: "Champs-Élysées, Paris",
    capacity: 1000,
    remainingSeats: 200,
    category: "Sport",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "9",
    title: "Conférence sur l'Intelligence Artificielle",
    description: "Explorez les dernières avancées en matière d'IA et leurs applications.",
    date: "2024-08-25",
    time: "14:00",
    location: "École Polytechnique, Paris",
    capacity: 250,
    remainingSeats: 150,
    category: "Technologie",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "10",
    title: "Exposition Florale",
    description: "Admirez les plus belles compositions florales et plantes exotiques.",
    date: "2024-05-10",
    time: "09:00",
    location: "Jardin Botanique, Nantes",
    capacity: 200,
    remainingSeats: 180,
    category: "Nature",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "11",
    title: "Dégustation de Vins",
    description: "Découvrez les meilleurs crus de la région en compagnie d'œnologues experts.",
    date: "2024-09-30",
    time: "19:00",
    location: "Château Viticole, Bordeaux",
    capacity: 50,
    remainingSeats: 20,
    category: "Gastronomie",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "12",
    title: "Concert Symphonique",
    description: "Un concert exceptionnel avec l'orchestre philharmonique de la ville.",
    date: "2024-12-15",
    time: "20:00",
    location: "Opéra Garnier, Paris",
    capacity: 400,
    remainingSeats: 150,
    category: "Musique",
    image: "/placeholder.svg?height=400&width=600",
  },
]
